x = int(input())

print(f"1 x {x} = {x}")
print(f"2 x {x} = {x*2}")
print(f"3 x {x} = {x*3}")
print(f"4 x {x} = {x*4}")
print(f"5 x {x} = {x*5}")
print(f"6 x {x} = {x*6}")
print(f"7 x {x} = {x*7}")
print(f"8 x {x} = {x*8}")
print(f"9 x {x} = {x*9}")
print(f"10 x {x} = {x*10}")